'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Activity
    Public Property ActivityName As String
    Public Property Active As Boolean
    Public Property Description As String
    Public Property isNumber As Boolean

    Public Overridable Property PersonActivities As ICollection(Of PersonActivity) = New HashSet(Of PersonActivity)

End Class
