'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DomainContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DomainContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Activities() As DbSet(Of Activity)
    Public Property People() As DbSet(Of Person)
    Public Property PersonActivities() As DbSet(Of PersonActivity)
    Public Property Routes() As DbSet(Of Route)
    Public Property Running() As DbSet(Of Running)

End Class
