'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Feedback
    Public Property Feedback1 As String
    Public Property Athelete As String
    Public Property EndDate As Date

    Public Overridable Property Person As Person

End Class
