'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonActivity
    Public Property Email As String
    Public Property ActivityName As String
    Public Property DayOfActivity As Date
    Public Property PAdescription As String
    Public Property isNumber As Boolean
    Public Property PAnumber As Nullable(Of Double)

    Public Overridable Property Activity As Activity
    Public Overridable Property Person As Person

End Class
