'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Person
    Public Property FName As String
    Public Property Email As String
    Public Property LName As String
    Public Property Admin As Boolean
    Public Property Passwd As String

    Public Overridable Property PersonActivities As ICollection(Of PersonActivity) = New HashSet(Of PersonActivity)
    Public Overridable Property Runnings As ICollection(Of Running) = New HashSet(Of Running)

End Class
