'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Route
    Public Property RouteName As String
    Public Property Distance As Single
    Public Property IsActive As Nullable(Of Boolean)

    Public Overridable Property Runnings As ICollection(Of Running) = New HashSet(Of Running)

End Class
