'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Running
    Public Property DayOfRunning As Date
    Public Property Email As String
    Public Property RouteName As String
    Public Property Miles As Integer

    Public Overridable Property Person As Person
    Public Overridable Property Route As Route

End Class
